fixed the issue where confirming a reviewed sighting wasn't redirecti…
techswitch-learners/Whale-spotting pull request #34
Opened 2021-04-07 13:55 UTC by emilypatsko

…ng (plus some minor styling fixes)

2021-04-08 11:53 UTC, chloejonessoftwire commented on Controllers/AdminController.cs
looks good to me!

2021-04-08 12:37 UTC, ChristianMcc reviewed
Looking good! Couple of small points on css and console.logs :)

2021-04-08 12:37 UTC, ChristianMcc commented on ClientApp/src/NavBar/NavBar.scss
> +  background-color: transparent !important;
can we find a way to do this without using !important keyword? take a look at https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity on how to do this and maybe a warning on not using important :)

2021-04-08 12:37 UTC, ChristianMcc commented on ClientApp/src/Pages/ConfirmSighting/ConfirmSighting.tsx
> +      console.log(status);
can delete this :)

2021-04-08 12:37 UTC, ChristianMcc commented on ClientApp/src/Pages/ConfirmSighting/ConfirmSighting.tsx
> +      console.log(status);
and here

2021-04-08 13:33 UTC, littlemauli reviewed
looks good to me

2021-04-08 17:42 UTC, ChristianMcc approved these changes

2021-04-08 17:43 UTC, ChristianMcc commented on Controllers/AdminController.cs
> -            if (!ModelState.IsValid)
how come we removed this? Is there not some validation on sighting that might be useful?

2021-04-08 17:44 UTC, ChristianMcc requested changes
Just a thought about modelstate being removed before we merge actually!

2021-04-08 21:44 UTC, emilypatsko commented on Controllers/AdminController.cs
> -            if (!ModelState.IsValid)
fixed it!

2021-04-09 06:54 UTC, ChristianMcc approved these changes

2021-04-09 08:02 UTC, merged